version: '3.7'
services:
  redis:
    image:
      redis
    ports:
      - "6379:6379"
    networks:
      - net
    volumes:
      - redis-v:/data
    command: ['redis-server', '--appendonly', 'yes']
  mongo:
    image:
      mongo
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - mongo-v:/data/db
  rabbit:
    image:
      rabbitmq:alpine
    ports:
      - "5672:5672"
    networks:
      - net
    restart: on-failure
  auctions:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo/my_database
      - AMQP_URL=amqp://guest:guest@rabbit:5672
    build: ./
    image: ic-auction
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - rabbit
      - redis
      - mongo
    restart: always
networks:
  net:
volumes:
  redis-v:
  mongo-v: